default_install_hook_types:
  - pre-commit
  - commit-msg
  # - pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: no-commit-to-branch
        args: [--pattern, '^(?!(feat|feature|fix|docs|style|refactor|test|chore)/\w+).+$']
      - id: pretty-format-json
        args: [--autofix, --indent, "4"]
        # args: [--autofix, --no-ensure-ascii, --indent, '2', --no-sort-keys]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  # - repo: https://github.com/tox-dev/pyproject-fmt
  #   rev: "1.7.0"
  #   hooks:
  #   - id: pyproject-fmt

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.2.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.17.1'
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML==6.0.12.20241230
          - pydantic
        args: ["--ignore-missing-imports", "--scripts-are-modules", "--config-file=pyproject.toml"]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
    - id: hadolint-docker

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.13
    hooks:
      - id: pip-compile
        name: pip-compile requirements.in
        args: [./requirements/requirements.in, -o, ./requirements/requirements.txt, --python-platform, linux, --python-version, '3.11']
        files: ^requirements/

      - id: pip-compile
        name: pip-compile requirements-dev.in
        args: [./requirements/requirements-dev.in, -o, ./requirements/requirements-dev.txt, --python-platform, linux, --python-version, '3.11']
        files: ^requirements/
        # project_root/.pre-commit-config.yaml
  #
  # - repo: local
  # hooks:
  # - id: commit-msg
  #     name: conventional commit messages
  #     language: pygrep
  #     entry: '^(chore|test|feat|fix|build|docs|refactor)!?(\([a-z]+\))?: (?![A-Z])(?![a-z]+(ed|ing)\s).*$'
  # args:
  # - --multiline
  # - --negate # fails if the entry is NOT matched
  # stages:
  # - commit-msg

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--verbose]
